#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using System.IO;
using Armada.Client.Core;
using Armada.Client.Playback;
using Newtonsoft.Json;
using UnityEditor;
using UnityEditor.SceneManagement;
using UnityEngine;
using UnityEngine.Rendering;

/// <summary>
/// Visual-regression capture harness, promoted from SpectatorCaptureSpike:
/// drives the REAL SpectatorRenderer through a committed resolved-battle
/// fixture (generated by scripts/visual/generate-capture-fixture.ts) with a
/// fixed deterministic tick, rendering offscreen PNG frames at pinned beats.
///
/// Modes (ARMADA_CAPTURE_MODE):
///  - "baseline" (default): the opening frame, the first tick of every turn
///    banner, and the completion frame — the small set diffed against the
///    committed baselines in tests/visual/baselines/.
///  - "sequence": every tick, for contact sheets / motion review
///    (reports-only output; never committed).
///
/// Env config: ARMADA_CAPTURE_FIXTURE (project-relative or absolute path to
/// the fixture JSON), ARMADA_CAPTURE_OUT (output directory; default
/// ../reports/unity/visual/&lt;fixture-name&gt;), ARMADA_CAPTURE_MODE.
///
/// Determinism contract (proven by the spike, SHA256-stable across runs):
/// never pass -nographics (offscreen rendering needs a graphics device);
/// render via camera.targetTexture + Camera.Render() + ReadPixels +
/// EncodeToPNG; pin RenderSettings.ambientMode/ambientLight; antiAliasing 1;
/// pin camera.aspect explicitly (batchmode has no game view to derive it
/// from, and the follow camera math reads it every tick).
///
/// Usage: -batchmode -quit -projectPath unity
///        -executeMethod SpectatorVisualCapture.Capture
/// </summary>
public static class SpectatorVisualCapture
{
    private const string DefaultFixturePath = "Assets/Editor/VisualCapture/Fixtures/pvp-seed11-focus-fire.json";
    private const int Width = 1920;
    private const int Height = 1080;
    // Fixed simulated tick; 0.1 s at speed x1 keeps every design-tunable
    // step duration (0.2–0.5 s) an exact multiple, so step boundaries land
    // on the same tick every run.
    private const float TickSeconds = 0.1f;
    // A 20-turn battle at ~10s of playback per turn is ~2000 ticks; anything
    // past this means playback stalled rather than finished.
    private const int SafetyTickLimit = 20000;

    // Mirrors PvPNetplayDemoSceneBuilder's stage exactly (camera, light,
    // board, colors); the capture is representative of the real PvP scenes.
    private const float CameraOrthographicSize = 8.5f;
    private static readonly Vector3 CameraPosition = new Vector3(11f, 20f, 0f);
    private static readonly Color BackgroundColor = new Color(0.03f, 0.08f, 0.15f);
    private static readonly Color BoardColor = new Color(0.07f, 0.22f, 0.36f);

    [Serializable]
    private sealed class CaptureFixture
    {
        public string Scenario { get; set; }
        public int Seed { get; set; }
        public int TurnLimit { get; set; }
        public string Description { get; set; }
        public SimWind Wind { get; set; }
        public List<SimShip> ShipsAtStart { get; set; }
        public List<Mission01TurnRecord> Turns { get; set; }
    }

    [Serializable]
    private sealed class CaptureManifest
    {
        public string Fixture { get; set; }
        public string Scenario { get; set; }
        public int Seed { get; set; }
        public string Mode { get; set; }
        public int TotalTicks { get; set; }
        public List<string> Frames { get; set; } = new List<string>();
        // Per-frame rendering stats (brief §5): "frame:batches=N,setpass=M".
        // The diff runner flags draw-call budget breaches from these.
        public List<string> FrameStats { get; set; } = new List<string>();
    }

    [MenuItem("Assets/Armada/Capture Spectator Visual Frames")]
    public static void Capture()
    {
        try
        {
            Run();
        }
        catch (Exception ex)
        {
            Fail(ex.ToString());
        }
    }

    private static void Run()
    {
        // Menu-path safety (same guard as every scene builder): the capture
        // replaces the open scene, so unsaved edits must be prompted for
        // first. Batchmode has no open user scene and no interactive prompt.
        if (!Application.isBatchMode && !EditorSceneManager.SaveCurrentModifiedScenesIfUserWantsTo())
        {
            return;
        }

        var fixturePath = Path.GetFullPath(
            Environment.GetEnvironmentVariable("ARMADA_CAPTURE_FIXTURE") ?? DefaultFixturePath);
        var mode = (Environment.GetEnvironmentVariable("ARMADA_CAPTURE_MODE") ?? "baseline")
            .ToLowerInvariant();
        if (mode != "baseline" && mode != "sequence")
        {
            Fail($"unknown ARMADA_CAPTURE_MODE '{mode}' (expected baseline or sequence)");
            return;
        }

        if (!File.Exists(fixturePath))
        {
            Fail($"fixture not found: {fixturePath}");
            return;
        }

        var fixture = JsonConvert.DeserializeObject<CaptureFixture>(File.ReadAllText(fixturePath));
        if (fixture?.ShipsAtStart == null || fixture.Turns == null || fixture.Turns.Count == 0)
        {
            Fail($"fixture is empty or malformed: {fixturePath}");
            return;
        }

        var fixtureName = Path.GetFileNameWithoutExtension(fixturePath);
        var outDir = Path.GetFullPath(
            Environment.GetEnvironmentVariable("ARMADA_CAPTURE_OUT")
            ?? Path.Combine("..", "reports", "unity", "visual", fixtureName));
        Directory.CreateDirectory(outDir);

        EditorSceneManager.NewScene(NewSceneSetup.EmptyScene, NewSceneMode.Single);

        // Pin ambient so frames never depend on a lighting bake.
        RenderSettings.ambientMode = AmbientMode.Flat;
        RenderSettings.ambientLight = new Color(0.35f, 0.38f, 0.42f);

        var camera = BuildStage();
        var spectator = BuildSpectator(camera);

        spectator.BeginTurns(
            fixture.ShipsAtStart,
            fixture.Turns,
            fixture.TurnLimit,
            introLine: $"Capturing {fixture.Scenario} (seed {fixture.Seed})...",
            completionLine: "Capture complete",
            wind: fixture.Wind);

        var manifest = new CaptureManifest
        {
            Fixture = fixtureName,
            Scenario = fixture.Scenario,
            Seed = fixture.Seed,
            Mode = mode
        };

        var target = new RenderTexture(Width, Height, 24, RenderTextureFormat.ARGB32)
        {
            antiAliasing = 1
        };
        var readback = new Texture2D(Width, Height, TextureFormat.RGB24, false);

        try
        {
            CaptureFrame(camera, target, readback, outDir, manifest, "frame-00000-opening");

            var tick = 0;
            var lastBannerTurn = 0;
            while (!spectator.IsFinished && tick < SafetyTickLimit)
            {
                spectator.Tick(TickSeconds);
                tick++;

                var step = spectator.CurrentStep;
                var isNewBanner = step != null
                    && step.Kind == PlaybackStepKind.TurnStart
                    && step.Turn != lastBannerTurn;
                if (isNewBanner)
                {
                    lastBannerTurn = step.Turn;
                }

                if (mode == "sequence")
                {
                    CaptureFrame(camera, target, readback, outDir, manifest, $"frame-{tick:D5}");
                }
                else if (isNewBanner)
                {
                    CaptureFrame(camera, target, readback, outDir, manifest,
                        $"frame-{tick:D5}-turn{lastBannerTurn:D2}");
                }
            }

            if (!spectator.IsFinished)
            {
                Fail($"playback did not finish within {SafetyTickLimit} ticks");
                return;
            }

            CaptureFrame(camera, target, readback, outDir, manifest, $"frame-{tick + 1:D5}-complete");
            manifest.TotalTicks = tick;

            File.WriteAllText(
                Path.Combine(outDir, "manifest.json"),
                JsonConvert.SerializeObject(manifest, Formatting.Indented) + "\n");
            Debug.Log($"[SpectatorVisualCapture] {manifest.Frames.Count} frames ({mode}) -> {outDir}");
        }
        finally
        {
            UnityEngine.Object.DestroyImmediate(readback);
            UnityEngine.Object.DestroyImmediate(target);
        }
    }

    private static Camera BuildStage()
    {
        var cameraObject = new GameObject("Main Camera", typeof(Camera));
        var camera = cameraObject.GetComponent<Camera>();
        camera.orthographic = true;
        camera.orthographicSize = CameraOrthographicSize;
        camera.clearFlags = CameraClearFlags.SolidColor;
        camera.backgroundColor = BackgroundColor;
        // Batchmode has no game view; the follow camera reads aspect every
        // tick, so it must be pinned to the capture resolution explicitly.
        camera.aspect = (float)Width / Height;
        cameraObject.transform.position = CameraPosition;
        cameraObject.transform.rotation = Quaternion.Euler(90f, 0f, 0f);

        var lightObject = new GameObject("Directional Light", typeof(Light));
        var light = lightObject.GetComponent<Light>();
        light.type = LightType.Directional;
        lightObject.transform.rotation = Quaternion.Euler(50f, -30f, 0f);

        var board = GameObject.CreatePrimitive(PrimitiveType.Cube);
        board.name = "Board";
        board.transform.position = new Vector3(11f, -0.55f, 0f);
        board.transform.localScale = new Vector3(140f, 1f, 120f);
        board.GetComponent<Renderer>().sharedMaterial = new Material(Shader.Find("Universal Render Pipeline/Lit"))
        {
            color = BoardColor
        };

        return camera;
    }

    private static SpectatorRenderer BuildSpectator(Camera camera)
    {
        var spectatorObject = new GameObject("Spectator", typeof(SpectatorRenderer));
        var spectator = spectatorObject.GetComponent<SpectatorRenderer>();
        // Same wiring as the PvP scene builders: the renderer re-frames this
        // camera every tick, never zooming tighter than the authored 8.5.
        // hudLabel stays null deliberately — captures must not depend on the
        // TMP Essentials import; the renderer null-guards the label.
        var serialized = new SerializedObject(spectator);
        var property = serialized.FindProperty("followCamera");
        property.objectReferenceValue = camera;
        serialized.ApplyModifiedPropertiesWithoutUndo();
        // Same view provider as the generated scenes (greybox prefabs with
        // primitive fallback), so captures show what the scenes show.
        ShipViewProviderWiring.Attach(spectator);
        return spectator;
    }

    private static void CaptureFrame(
        Camera camera,
        RenderTexture target,
        Texture2D readback,
        string outDir,
        CaptureManifest manifest,
        string name)
    {
        camera.targetTexture = target;
        camera.Render();
        camera.targetTexture = null;

        var previous = RenderTexture.active;
        RenderTexture.active = target;
        readback.ReadPixels(new Rect(0f, 0f, Width, Height), 0, 0);
        readback.Apply();
        RenderTexture.active = previous;

        var png = readback.EncodeToPNG();
        if (png == null || png.Length == 0)
        {
            throw new InvalidOperationException($"EncodeToPNG produced no bytes for {name}");
        }

        var fileName = $"{name}.png";
        File.WriteAllBytes(Path.Combine(outDir, fileName), png);
        manifest.Frames.Add(fileName);
        manifest.FrameStats.Add(
            $"{name}:batches={UnityEditor.UnityStats.batches},setpass={UnityEditor.UnityStats.setPassCalls}");
    }

    private static void Fail(string reason)
    {
        Debug.LogError($"[SpectatorVisualCapture] Capture failed: {reason}");
        if (Application.isBatchMode)
        {
            EditorApplication.Exit(1);
        }
    }
}
#endif
